# Site settings
title: Chamara Abesinghe | An anomaly of Matrix
description: This is my personal web space. Take a look around.
baseurl: "/me"
url: "https://super-chama.github.io"

# User settings
username: Chamara Abesignhe
user_description: I'm a Professional Video Editor & Motion graphics artist with more than 2 years of experience. And an undergraduate of University of Westminister studying Software development.
user_title: Video Editor | Software Developer
email: chamaa@boun.cr
twitter_username: "@ChamaraVFX"
github_username:  super-chama
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
